const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function auditSponsorChange() {
    const mobile = '9953869409';
    console.log(`Auditing sponsor change for ${mobile}...`);

    try {
        const user = await prisma.user.findUnique({
            where: { mobile },
            include: { sponsor: true }
        });

        if (!user) {
            console.error('User not found');
            return;
        }

        console.log(`Current Sponsor: ${user.sponsor ? user.sponsor.mobile : 'NONE'}`);

        // Find commissions generated by this user
        const commissions = await prisma.transaction.findMany({
            where: {
                fromUserId: user.id,
                category: 'BONUS'
            },
            include: { user: true }
        });

        if (commissions.length === 0) {
            console.log('No commissions found for this user yet.');
        } else {
            console.log('\nPast Commissions:');
            commissions.forEach(c => {
                console.log(`- ${c.amount}/- sent to ${c.user.mobile} (${c.user.name || '-'}) on ${c.createdAt.toISOString()}`);
            });
        }

        // New Sponsor details
        const newSponsorMobile = '9210021221';
        const newSponsor = await prisma.user.findUnique({
            where: { mobile: newSponsorMobile },
            include: { wallets: true }
        });

        if (newSponsor) {
            const cashWallet = newSponsor.wallets.find(w => w.type === 'CASH');
            console.log(`\nNew Sponsor (${newSponsorMobile}) current balance: ₹${cashWallet ? cashWallet.balance : 0}`);
        }

    } catch (e) {
        console.error(e);
    } finally {
        await prisma.$disconnect();
    }
}

auditSponsorChange();
